# Generated by Django 2.2.3 on 2019-08-01 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_machine', models.CharField(max_length=50)),
                ('process_machine', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_factory', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('average_production', models.IntegerField()),
                ('id_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Machine')),
            ],
        ),
    ]
