# Generated by Django 2.2.3 on 2019-08-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190801_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_process', models.CharField(max_length=50)),
                ('id_machine', models.ManyToManyField(to='core.Machine')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='id_process',
            field=models.ManyToManyField(to='core.Process'),
        ),
    ]
