# Generated by Django 2.2.3 on 2019-08-01 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190801_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('name_material', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFinisehd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=50)),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Material')),
                ('id_process', models.ManyToManyField(to='core.Process')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('queality', models.IntegerField()),
                ('id_material', models.ManyToManyField(to='core.Material')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='id_order',
            field=models.ManyToManyField(to='core.Order'),
        ),
    ]
