# Generated by Django 2.2.3 on 2019-08-01 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190801_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='id_order',
        ),
    ]
