# Generated by Django 2.2.3 on 2019-08-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190801_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessMachineForTime',
            fields=[
                ('id_time_process', models.AutoField(primary_key=True, serialize=False)),
                ('time_process', models.IntegerField()),
                ('id_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Machine')),
                ('id_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Process')),
            ],
        ),
    ]
